### ISSUE TITLE
Отхождение от ТЗ

### ISSUE THREAD

**Issue by baileys-li** [bazarovstas/supergym#1]
> При клике на "Купить абонемент" скролл страницы до раздела Абонементы. 

Сейчас просто пустая якорная ссылка

**Comment by baileys-li** [comment]
Нет градиента при ховере/фокусе
![image](https://user-images.githubusercontent.com/47776594/213275331-1f38844e-3ac7-4f47-b869-47a4e9dfdd85.png)

**Comment by bazarovstas** [comment]
Исправлено
