### ISSUE TITLE
Отхождения от БЭМ

### ISSUE THREAD

**Issue by baileys-li** [bazarovstas/supergym#2]
![image](https://user-images.githubusercontent.com/47776594/213273472-f113c625-d7ff-41d6-9ad0-f7b9146ae5bc.png)
![image](https://user-images.githubusercontent.com/47776594/213273511-9ba75d58-4b6c-4f05-9d69-c047083dc25a.png)
![image](https://user-images.githubusercontent.com/47776594/213273560-f31bbdc4-5a48-4b36-90b5-0d3e0b1bc1c7.png)

**Comment by bazarovstas** [comment]
Исправлено
